config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'
  get 'pages/home'
  get 'pages/about'
  resources :committees
  resources :administrations
  resources :faculties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administration.rb
class Administration < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/committee.rb
class Committee < ApplicationRecord
end

app/models/faculty.rb
class Faculty < ApplicationRecord
end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController
  before_action :set_administration, only: [:show, :edit, :update, :destroy]

  # GET /administrations
  # GET /administrations.json
  def index
    @administrations = Administration.all
  end

  # GET /administrations/1
  # GET /administrations/1.json
  def show
  end

  # GET /administrations/new
  def new
    @administration = Administration.new
  end

  # GET /administrations/1/edit
  def edit
  end

  # POST /administrations
  # POST /administrations.json
  def create
    @administration = Administration.new(administration_params)

    respond_to do |format|
      if @administration.save
        format.html { redirect_to @administration, notice: 'Administration was successfully created.' }
        format.json { render :show, status: :created, location: @administration }
      else
        format.html { render :new }
        format.json { render json: @administration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrations/1
  # PATCH/PUT /administrations/1.json
  def update
    respond_to do |format|
      if @administration.update(administration_params)
        format.html { redirect_to @administration, notice: 'Administration was successfully updated.' }
        format.json { render :show, status: :ok, location: @administration }
      else
        format.html { render :edit }
        format.json { render json: @administration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrations/1
  # DELETE /administrations/1.json
  def destroy
    @administration.destroy
    respond_to do |format|
      format.html { redirect_to administrations_url, notice: 'Administration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administration
      @administration = Administration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administration_params
      params.require(:administration).permit(:adminID, :firstname, :lastname, :title, :extension)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :set_committee, only: [:show, :edit, :update, :destroy]

  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
  end

  # GET /committees/new
  def new
    @committee = Committee.new
  end

  # GET /committees/1/edit
  def edit
  end

  # POST /committees
  # POST /committees.json
  def create
    @committee = Committee.new(committee_params)

    respond_to do |format|
      if @committee.save
        format.html { redirect_to @committee, notice: 'Committee was successfully created.' }
        format.json { render :show, status: :created, location: @committee }
      else
        format.html { render :new }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committees/1
  # PATCH/PUT /committees/1.json
  def update
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to @committee, notice: 'Committee was successfully updated.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee.destroy
    respond_to do |format|
      format.html { redirect_to committees_url, notice: 'Committee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committee
      @committee = Committee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_params
      params.require(:committee).permit(:committeeID, :comitname, :facultyID, :meetday)
    end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:facultyID, :fName, :lName, :department, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/administrations_helper.rb
module AdministrationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/administrations/_form.html.erb
<%= form_with(model: administration, local: true) do |form| %>
  <% if administration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administration.errors.count, "error") %> prohibited this administration from being saved:</h2>

      <ul>
      <% administration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :adminID %>
    <%= form.number_field :adminID %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :extension %>
    <%= form.text_field :extension %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/administrations/edit.html.erb
<h1>Editing Administration</h1>

<%= render 'form', administration: @administration %>

<%= link_to 'Show', @administration %> |
<%= link_to 'Back', administrations_path %>

app/views/administrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administrations</h1>

<table>
  <thead>
    <tr>
      <th>Adminid</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Title</th>
      <th>Extension</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrations.each do |administration| %>
      <tr>
        <td><%= administration.adminID %></td>
        <td><%= administration.firstname %></td>
        <td><%= administration.lastname %></td>
        <td><%= administration.title %></td>
        <td><%= administration.extension %></td>
        <td><%= link_to 'Show', administration %></td>
        <td><%= link_to 'Edit', edit_administration_path(administration) %></td>
        <td><%= link_to 'Destroy', administration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administration', new_administration_path %>

app/views/administrations/new.html.erb
<h1>New Administration</h1>

<%= render 'form', administration: @administration %>

<%= link_to 'Back', administrations_path %>

app/views/administrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adminid:</strong>
  <%= @administration.adminID %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @administration.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @administration.lastname %>
</p>

<p>
  <strong>Title:</strong>
  <%= @administration.title %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @administration.extension %>
</p>

<%= link_to 'Edit', edit_administration_path(@administration) %> |
<%= link_to 'Back', administrations_path %>

app/views/committees/_form.html.erb
<%= form_with(model: committee, local: true) do |form| %>
  <% if committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :committeeID %>
    <%= form.number_field :committeeID %>
  </div>

  <div class="field">
    <%= form.label :comitname %>
    <%= form.text_field :comitname %>
  </div>

  <div class="field">
    <%= form.label :facultyID %>
    <%= form.number_field :facultyID %>
  </div>

  <div class="field">
    <%= form.label :meetday %>
    <%= form.text_field :meetday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing Committee</h1>

<%= render 'form', committee: @committee %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Committees</h1>

<table>
  <thead>
    <tr>
      <th>Committeeid</th>
      <th>Comitname</th>
      <th>Facultyid</th>
      <th>Meetday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= committee.committeeID %></td>
        <td><%= committee.comitname %></td>
        <td><%= committee.facultyID %></td>
        <td><%= committee.meetday %></td>
        <td><%= link_to 'Show', committee %></td>
        <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
        <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Committee', new_committee_path %>

app/views/committees/new.html.erb
<h1>New Committee</h1>

<%= render 'form', committee: @committee %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Committeeid:</strong>
  <%= @committee.committeeID %>
</p>

<p>
  <strong>Comitname:</strong>
  <%= @committee.comitname %>
</p>

<p>
  <strong>Facultyid:</strong>
  <%= @committee.facultyID %>
</p>

<p>
  <strong>Meetday:</strong>
  <%= @committee.meetday %>
</p>

<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :facultyID %>
    <%= form.number_field :facultyID %>
  </div>

  <div class="field">
    <%= form.label :fName %>
    <%= form.text_field :fName %>
  </div>

  <div class="field">
    <%= form.label :lName %>
    <%= form.text_field :lName %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faculties</h1>

<table>
  <thead>
    <tr>
      <th>Facultyid</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Department</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.facultyID %></td>
        <td><%= faculty.fName %></td>
        <td><%= faculty.lName %></td>
        <td><%= faculty.department %></td>
        <td><%= faculty.email %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Facultyid:</strong>
  <%= @faculty.facultyID %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @faculty.fName %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @faculty.lName %>
</p>

<p>
  <strong>Department:</strong>
  <%= @faculty.department %>
</p>

<p>
  <strong>Email:</strong>
  <%= @faculty.email %>
</p>

<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Krokoszsecondexam" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Krokoszsecondexam</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>